version: '3.8'

services:
  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - SERVICE_NAME=report-service
      - SNOWFLAKE_ACCOUNT=BIREZNC-ZHB27778
      - SNOWFLAKE_USER=SAURABHMAC
      - SNOWFLAKE_PASSWORD=AwsSnowAdmin1234
      - SNOWFLAKE_DATABASE=analytics_platform
      - SNOWFLAKE_WAREHOUSE=analytics_wh
      - SNOWFLAKE_SCHEMA=reporting
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - snowflake-network

  streamlit-service:
    build:
      context: ./streamlit-app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_BASE=light
      - SERVICE_NAME=streamlit-cortex-analyst
      - SNOWFLAKE_ACCOUNT=BIREZNC-ZHB27778
      - SNOWFLAKE_USER=SAURABHMAC
      - SNOWFLAKE_PASSWORD=AwsSnowAdmin1234
      - SNOWFLAKE_DATABASE=analytics_platform
      - SNOWFLAKE_WAREHOUSE=analytics_wh
      - SNOWFLAKE_SCHEMA=reporting
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - snowflake-network
    depends_on:
      - report-service

networks:
  snowflake-network:
    driver: bridge
    name: snowflake-analytics-network