[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = true
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1a202c"

[client]
caching = true
displayEnabled = true
showErrorDetails = true

[logger]
level = "info"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true